### ISSUE TITLE
Input type=search not working

### ISSUE THREAD

**Issue by bcomnes** [yoshuawuyts/nanomorph#50]
When typing into an input search input box, the input is cleared every time, which is a behavioral difference to morphdom.

**Comment by bcomnes** [comment]
Tested in choo 5, but swapping out for morphdom is getting the same behavior. Hrmm....

**Comment by yoshuawuyts** [comment]
Have you set the "value" property to be what the latest value is?

**Comment by bcomnes** [comment]
No, in this case I didn't.  I'll try that, but this would be a behavior change from choo4.

**Comment by yoshuawuyts** [comment]
> but this would be a behavior change from choo4

That's correct - the other behavior was kinda weird and treated input fields like one-off stateful things. That became annoying when you replaced one form with another, because the initial value would need to be cleared, which would need to be a manual action somehow in an `onload` selector.

Now that choo v5 is moving from an async event model to a sync one, it actually makes sense to keep the state and the value of the input in sync - if only so re-renders of the DOM actually become a function of state. Hope that makes sense! :sparkles:

**Comment by yoshuawuyts** [comment]
@bcomnes did this work?

**Comment by bcomnes** [comment]
Hey sorry for the delay. I'm almost sure this would work, I just haven't had a chance to test yet.

**Comment by bcomnes** [comment]
Yes, works!  Should we note this in the changelog of Choo?

**Comment by yoshuawuyts** [comment]
@bcomnes yeah we def should! :sparkles:
